version: '3.3'
services:
  db:
    image: postgres:latest
    command: -c max_connections=500
    volumes:
      - .volumes/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust