DROP INDEX idx_schedule_matches_id;
DROP INDEX idx_schedule_matches_team_a_name;
DROP INDEX idx_schedule_matches_team_b_name;
DROP INDEX idx_game_games_id;
DROP INDEX idx_game_games_match_id;
DROP INDEX idx_game_games_stats_game_id;